CREATE TABLE PEOPLE
(
	ID INT IDENTITY(1,1) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	POSITION VARCHAR(64) NOT NULL,

	CONSTRAINT PEOPLE_PK PRIMARY KEY(ID)
)

CREATE TABLE RECORDS
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PERSON INT NOT NULL,
	ENTER DATETIME NOT NULL,
	LEAVE DATETIME NOT NULL,

	CONSTRAINT RECORDS_PK PRIMARY KEY(ID),
	CONSTRAINT RECORDS_PEOPLE_FK FOREIGN KEY(ID_PERSON) REFERENCES PEOPLE(ID)
)

CREATE TABLE ATWORK
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PERSON INT UNIQUE FOREIGN KEY REFERENCES PEOPLE(ID) NOT NULL,
	ENTER DATETIME NOT NULL,
	LEAVE DATETIME,

	CONSTRAINT ATWORK_PK PRIMARY KEY(ID), 
)